FROM ubuntu:18.04

EXPOSE 8080

WORKDIR /go/src/app

COPY . .

ENV PATH=$PATH:/usr/local/go/bin

ENV REQUEST_ORIGIN=http://localhost

RUN apt-get update && apt-get install wget -y \
    && apt-get install build-essential -y \
    && wget https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz \
    && rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.5.linux-amd64.tar.gz \
    && rm -rf go1.16.5.linux-amd64.tar.gz \
    && apt-get purge -y --auto-remove wget \
    && rm -rf /var/lib/apt/lists/* \
    && go build && go test ./... \
    && rm -rf /usr/local/go \
    && apt-get purge -y --auto-remove build-essential \
    && useradd -m appuser

USER appuser

CMD ["./server"]