version: '3' 

services:

    web:
      image: nginx
      ports:
        - 80:80
      container_name: web
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf

    db:
      image: postgres
      ports: 
        - 5432:5432
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      container_name: postgres
      volumes:
        - database:/var/lib/postgresql/data

    backend:  
      image: example-backend
      ports: 
        - 8080:8080
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      command: ["./server"]
      container_name: backend

    frontend:  
      image: example-frontend
      ports: 
        - 5000:5000
      command: ["serve", "-s", "-l", "5000", "build"]
      container_name: frontend

    redis:  
      image: redis
      ports: 
        - 6379:6379
      command: ["redis-server"]
      restart: unless-stopped
      container_name: redis

volumes:
  database: