FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt install -y nodejs && npm install && npm install -g serve \
    && apt-get purge -y --auto-remove curl \
    && rm -rf /var/lib/apt/lists/* \
    && npm run build && useradd -m appuser

ENV REACT_APP_BACKEND_URL=http://localhost:8080

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]