version: "3.8"
services:
  python-app:
    build: .
    environment:
        - REPOSITORY=${REPOSITORY}
        - IMAGE=${IMAGE}
    volumes:
      - ./:/code
    container_name: python-app

  watchtower:
    image: containrrr/watchtower
    environment:
        -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower