version: '3.7'

services:
    backend:
      build: ./bloglist-backend
      command: npm run dev
      ports: 
        - 3003:3003
      container_name: backend-bloglist
      volumes:
        - ./bloglist-backend:/usr/src/app
        - node_modules:/usr/src/app/node_modules

    frontend:
      build: ./bloglist-frontend
      command: npm start
      ports: 
        - 3000:3000
      container_name: frontend-bloglist
      volumes:
        - ./bloglist-frontend:/usr/src/app
        - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: