version: '3' 

services: 
    backend:  
      image: example-backend
      build: . 
      ports: 
        - 8080:8080 
      command: ["./server"]
      container_name: backend

    frontend:  
      image: example-frontend
      build: . 
      ports: 
        - 5000:5000 
      command: ["serve", "-s", "-l", "5000", "build"]
      container_name: frontend