FROM openjdk:8 as build-stage

WORKDIR /usr/src/myapp 

COPY . .

RUN ./mvnw clean install


FROM openjdk:8-jre-alpine

EXPOSE 8080

WORKDIR /usr/src/myapp

COPY --from=build-stage /usr/src/myapp/target/docker-example-1.1.3.jar /usr/src/myapp/target/docker-example-1.1.3.jar

RUN rm -rf /var/cache/apk/* \
    && adduser -S appuser

USER appuser

CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]